version: '3'

services:
  mariadb:
    image: mariadb:latest
    volumes:
      - mariadb-local:/var/lib/mysql
    networks:
      - mariadb_lan
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"

  adminer:
    depends_on:
      - mariadb
    image: adminer:4.2.5
    networks:
      - mariadb_lan
    ports:
      - "8080:8080"

volumes:
  mariadb-local:
    driver: local

networks:
  mariadb_lan:
    driver: bridge

# vim: ft=yaml et ts=2 sw=2 sts=2
