version: '3'

services:
  mariadb:
    image: mariadb:10.1.21
    volumes:
      - /srv/mariadb/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "T7s5SXXFY9"
    ports:
      - "3306:3306"

  adminer:
    depends_on:
      - mariadb
    image: adminer:4.2.5
    ports:
      - "8080:8080"

# vim: ft=yaml et ts=2 sw=2 sts=2
